name: ejemplo

on: 
 push:
 workflow_dispatch:

jobs:
  ejemplo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3.7.0
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: cazziwork/create-release-note@v1.0.0
